<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE HEADER-->
        <!-- BEGIN PAGE HEAD -->
        <div class="page-head">
            <div class="page-title">
                <h1>Wahlen zur Projektwoche <?= date('Y') ?> <small><?= $_SESSION['proWoTopic'] ?></small></h1>
            </div>

        </div>
        <!-- END PAGE HEAD -->
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="portlet light">
            <div class="portlet-body">
                <!--/row-->
                <!-- Meer Our Team -->
                <div class="headline">
                    <h3></h3>
                </div>
                <div class="row thumbnails">

<p>
    <?php
    $wlcTxt = DB::queryFirstRow("SELECT welcomeMessage FROM config WHERE id=%s", '1');
    echo $wlcTxt['welcomeMessage'];
    ?>
</p>

                </div>
                <!--/thumbnails-->
                <!-- //End Meer Our Team -->
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
</div>
<!-- END CONTENT -->
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
