<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- /.modal -->
        <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
        <!-- BEGIN PAGE HEADER-->
        <!-- BEGIN PAGE HEAD -->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title">
                <h1>Deine Wahl <small></small></h1>
            </div>
            <!-- END PAGE TITLE -->
        </div>
        <!-- END PAGE HEAD -->
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="portlet light">
            <div class="portlet-body">
                <div class="row">
                    <div class="col-md-12">
                        <?php

                        $yourVote= DB::queryFirstRow("SELECT * FROM voteRelas WHERE userId=%s", $_SESSION['account_id']);
                        $yourVote= DB::queryFirstRow("SELECT * FROM project WHERE id=%s", $yourVote['projectId']);

                        ?>
                        <div class="col-md-3">
                            <div class="meet-our-team">
                                <h3><small>Nr.: <?= $yourVote['projectNr'] ?></small> <br>
                                    <?= $yourVote['title'] ?>
                                </h3>
                                <div class="team-info">
                                    <p>
                                        <?= $yourVote['text'] ?>
                                    </p>
                                    <b>Klasse:</b> <?= $yourVote['startClass'] ?> - <?= $yourVote['endClass'] ?> <br>
                                    <b>Max. Teilnehmer:</b> <?= $yourVote['maxUsers'] ?><br>
                                    <b>Lehrkraft:</b> <?= $yourVote['projectLeader'] ?><br>

                                    <br>
                                    <br>
                                    <a href="/prowo/<?= $yourVote['projectNr'].'.pdf' ?>" target="_blank">'Projekt zum Download'</a><br>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT-->
    </div>
</div>
<!-- END CONTENT -->