<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
        <!-- BEGIN PAGE HEADER-->
        <!-- BEGIN PAGE HEAD -->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title">
                <h1>Projekt anlegen </h1>
            </div>

        </div>
        <!-- END PAGE HEAD -->
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN PORTLET-->
                <?php
                if(isset($error_message) AND $error_message == true){
                   echo '<div class="Metronic-alerts alert alert-danger fade in" id="prefix_549034258045">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button"></button>
                '.$error_message.'</div>
                ';}
                if(isset($success_message) AND $success_message == true){
                    echo '<div class="alert alert-success">
								<strong>Erfolgreich!</strong> Das Projekt wurde hinzugefügt.
							</div>';
                }


                ?>
                <div class="portlet box yellow-crusta">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-gift"></i>
                            Projekterfassung
                        </div>
                    </div>

                    <div class="portlet-body form">
                        <form action="/addProject" method="post" id="form-username" class="form-horizontal form-bordered">
                            <div class="form-group ">
                                <label class="col-sm-3 control-label">Projekt-Nr.:</label>
                                <div class="col-sm-6">
                                    <div class="input-group">
                                        <input type="text" id="typeahead_example_6" name="projectNr" <?php if(isset($userdata['projectNr'])){echo ' value="'.$userdata['projectNr'].'"';}  ?> class="form-control" />
                                    </div>
                                    <p class="help-block">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group ">
                                <label class="col-sm-3 control-label">Name des Projekts</label>
                                <div class="col-sm-6">
                                    <div class="input-group">
                                        <input type="text" id="typeahead_example_6" name="projectname" <?php if(isset($userdata['projectname'])){echo ' value="'.$userdata['projectname'].'"';}  ?> class="form-control" />
                                    </div>
                                    <p class="help-block">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group ">
                                <label class="col-sm-3 control-label">Projektleiter</label>
                                <div class="col-sm-6">
                                    <div class="input-group">
                                        <input type="text" id="typeahead_example_6" name="projectLeader" <?php if(isset($userdata['projectLeader'])){echo 'value="'.$userdata['projectLeader'].'"';}  ?>  class="form-control"/>
                                    </div>
                                    <p class="help-block">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group ">
                                <label class="col-sm-3 control-label">Land</label>
                                <div class="col-sm-6">
                                    <div class="input-group">
                                        <input type="text" id="typeahead_example_6" name="projectLand" <?php if(isset($userdata['projectLand'])){echo 'value="'.$userdata['projectLand'].'"';}  ?>  class="form-control"/>
                                    </div>
                                    <p class="help-block">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Max. Schüler</label>
                                <div class="col-md-4">
                                    <select class="form-control input-xsmall" name="maxpeo">
                                        <option value="2" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '2'){echo 'selected';}  ?>>2</option>
                                        <option value="5" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '5'){echo 'selected';}  ?>>5</option>
                                        <option value="6" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '6'){echo 'selected';}  ?>>6</option>
                                        <option value="7" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '7'){echo 'selected';}  ?>>7</option>
                                        <option value="8" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '8'){echo 'selected';}  ?>>8</option>
                                        <option value="9" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '9'){echo 'selected';}  ?>>9</option>
                                        <option value="10" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '10'){echo 'selected';}  ?>>10</option>
                                        <option value="11" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '11'){echo 'selected';}  ?>>11</option>
                                        <option value="12" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '12'){echo 'selected';}  ?>>12</option>
                                        <option value="13" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '13'){echo 'selected';}  ?>>13</option>
                                        <option value="14" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '14'){echo 'selected';}  ?>>14</option>
                                        <option value="15" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '15'){echo 'selected';}  ?>>15</option>
                                        <option value="16" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '16'){echo 'selected';}  ?>>16</option>
                                        <option value="17" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '17'){echo 'selected';}  ?>>17</option>
                                        <option value="18" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '18'){echo 'selected';}  ?>>18</option>
                                        <option value="19" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '19'){echo 'selected';}  ?>>19</option>
                                        <option value="20" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '20'){echo 'selected';}  ?>>20</option>
                                        <option value="21" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '21'){echo 'selected';}  ?>>21</option>
                                        <option value="22" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '22'){echo 'selected';}  ?>>22</option>
                                        <option value="23" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '23'){echo 'selected';}  ?>>23</option>
                                        <option value="24" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '24'){echo 'selected';}  ?>>24</option>
                                        <option value="25" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '25'){echo 'selected';}  ?>>25</option>
                                        <option value="26" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '26'){echo 'selected';}  ?>>26</option>
                                        <option value="27" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '27'){echo 'selected';}  ?>>27</option>
                                        <option value="28" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '28'){echo 'selected';}  ?>>28</option>
                                        <option value="29" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '29'){echo 'selected';}  ?>>29</option>
                                        <option value="30" <?php if(isset($userdata['maxpeo']) AND $userdata['maxpeo'] == '30'){echo 'selected';}  ?>>30</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Angebot für Klassen</label>
                                <div class="col-md-4">Von:
                                    <select class="form-control input-xsmall" name="minclass">
                                        <option value="5" <?php if(isset($userdata['minclass']) AND $userdata['minclass'] == '5'){echo 'selected';}  ?>>5 Kl.</option>
                                        <option value="6" <?php if(isset($userdata['minclass']) AND $userdata['minclass'] == '6'){echo 'selected';}  ?>>6 Kl.</option>
                                        <option value="7" <?php if(isset($userdata['minclass']) AND $userdata['minclass'] == '7'){echo 'selected';}  ?>>7 Kl.</option>
                                        <option value="8" <?php if(isset($userdata['minclass']) AND $userdata['minclass'] == '8'){echo 'selected';}  ?>>8 Kl.</option>
                                        <option value="9" <?php if(isset($userdata['minclass']) AND $userdata['minclass'] == '9'){echo 'selected';}  ?>>9 Kl.</option>
                                        <option value="10" <?php if(isset($userdata['minclass']) AND $userdata['minclass'] == '10'){echo 'selected';}  ?>>10 Kl.</option>
                                        <option value="11" <?php if(isset($userdata['minclass']) AND $userdata['minclass'] == '11'){echo 'selected';}  ?>>11 Kl.</option>
                                    </select>
                                    bis:
                                    <select class="form-control input-xsmall" name="maxclass">
                                        <option value="5" <?php if(isset($userdata['maxclass']) AND $userdata['maxclass'] == '5'){echo 'selected';}  ?>>5 Kl.</option>
                                        <option value="6" <?php if(isset($userdata['maxclass']) AND $userdata['maxclass'] == '6'){echo 'selected';}  ?>>6 Kl.</option>
                                        <option value="7" <?php if(isset($userdata['maxclass']) AND $userdata['maxclass'] == '7'){echo 'selected';}  ?>>7 Kl.</option>
                                        <option value="8" <?php if(isset($userdata['maxclass']) AND $userdata['maxclass'] == '8'){echo 'selected';}  ?>>8 Kl.</option>
                                        <option value="9" <?php if(isset($userdata['maxclass']) AND $userdata['maxclass'] == '9'){echo 'selected';}  ?>>9 Kl.</option>
                                        <option value="10" <?php if(isset($userdata['maxclass']) AND $userdata['maxclass'] == '10'){echo 'selected';}  ?>>10 Kl.</option>
                                        <option value="11" <?php if(isset($userdata['maxclass']) AND $userdata['maxclass'] == '11'){echo 'selected';}  ?>>11 Kl.</option>
                                    </select>
                                </div>
                            </div>
                            <div class="form-group ">
                                <label class="col-sm-3 control-label">Raumwunsch?</label>
                                <div class="col-sm-6">
                                    <div class="input-group">
                                        <input type="text" id="typeahead_example_6" name="roomwish" <?php if(isset($userdata['roomwish'])){echo 'value="'.$userdata['roomwish'].'"';}  ?> class="form-control"/>
                                    </div>
                                    <p class="help-block">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" rows="3=6" placeholder="Projekt - Inhalt" name="projectdesc"><?php if(isset($userdata['projectdesc'])){echo $userdata['projectdesc'];}  ?></textarea>
                            </div>

                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">

                                        <button type="submit" class="btn purple" name="addproject"><i class="fa fa-check"></i> Hinzufügen</button>

                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- END PORTLET-->
            </div>
        </div>

