    <!-- BEGIN CONTENT -->
    <div class="page-content-wrapper">
        <div class="page-content">
            <!-- BEGIN PAGE HEADER-->
            <!-- BEGIN PAGE HEAD -->
            <div class="page-head">
                <div class="page-title">
                    <h1>Wahlen zur Projektwoche 2015 <small>Die Welt als .......</small></h1>
                </div>

            </div>
            <!-- END PAGE HEAD -->
            <!-- END PAGE HEADER-->
            <!-- BEGIN PAGE CONTENT-->
            <div class="portlet light">
                <div class="portlet-body">
                    <!--/row-->
                    <!-- Meer Our Team -->
                    <div class="headline">
                        <h3></h3>
                    </div>
                    <div class="row thumbnails">


<?php

if(isset($results)){
foreach ($results as $row) {
    ?>
    <div class="col-md-3">
        <div class="meet-our-team">

            <h3><small> </small><?= $row['projectNr'] ?>  <?= $row['title'] ?></h3>

            <form method="post" action="/admEditProjekt">
            <button type="submit" name="delProjekt" value="<?= $row['id']?>"  class="btn btn-icon-only red fa fa-times"></button>
            <button type="submit" name="editProjekt"  value="<?= $row['id']?>" class="btn btn-icon-only yellow fa fa-pencil"></button>
            </form>

            <div class="team-info">
                <b>Beschreibung:</b>
                <p>
                    <?= $row['text'] ?>
                </p>
                <b>Land:</b>
                <p>
                    <?= $row['projectLand'] ?>
                </p>
                <b>Klasse:</b>
                <p>
                    <?= $row['startClass'] ?> - <?= $row['endClass'] ?>
                </p>
                <b>Max. Teilnehmer:</b> <?= $row['maxUsers'] ?><br>
                <b>Teilnehmer (aktuell):</b> <?= $row['nowUsers'] ?><br>
                <?php
                $rest = $row['maxUsers'] - $row['nowUsers'];
                ?>
                <b>Restplätze:</b> <?= $rest ?><br>
                <b>Projektleiter:</b> <?= $row['projectLeader'] ?><br>
            </div>
        </div>
    </div>
<?php
}

}
?>



                    </div>
                    <!--/thumbnails-->
                    <!-- //End Meer Our Team -->

                </div>

            </div>
            <!-- END PAGE CONTENT-->
        </div>
    </div>
    <!-- END CONTENT -->
</div>
<!-- END CONTAINER -->
<!-- BEGIN FOOTER -->
