<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
        <!-- BEGIN PAGE HEADER-->
        <!-- BEGIN PAGE HEAD -->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title">
                <h1>ProWo - 2015 </h1>
            </div>

        </div>
        <!-- END PAGE HEAD -->
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->

        <div class="row">
            <div class="col-md-12">
                <?php
                if(isset($error_message) AND $error_message == true){
                    echo '<div class="Metronic-alerts alert alert-danger fade in" id="prefix_549034258045">
                <button aria-hidden="true" data-dismiss="alert" class="close" type="button"></button>
                '.$error_message.'</div>
                ';}
                if(isset($success_message) AND $success_message == true){
                    echo '<div class="alert alert-success">
								<strong>Erfolgreich!</strong> Änderungen wurden übernommen.
							</div>';
                }


                ?>
                <!-- BEGIN PORTLET-->
                <div class="portlet box yellow-crusta">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-gift"></i>
                            Projekte - Import
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <form action="/importProj" id="form-username" method="post" class="form-horizontal form-bordered" enctype="multipart/form-data">

                            <div class="form-group">
                                <label class="control-label col-md-3">Beispiel der CSV-Datei</label>
                                <div class="col-md-9">
                                    <p>
                                        Nr;Land;Name;Aktivitäten;Lehrer;Anzahl;Klassen;Raumwunsch;<br>
                                        1;Brasilien;Eine Seefahrt nach Rio;und vorher einstudieren;Ewe + Schülerin;25;5,6;Musik, Aula;
                                        <br><br>
                                        Datei als utf8 formatiert!
                                    </p>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-3 control-label" for="exampleInputFile" >File input</label>
                                <div class="col-md-9">
                                    <input type="file" id="exampleInputFile" name="uploadedFile">
                                    <p class="help-block">
                                        some help text here.
                                    </p>
                                </div>
                            </div>



                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <button type="submit" class="btn purple"><i class="fa fa-check"></i> Speichern</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- END PORTLET-->
            </div>
        </div>



