<!-- BEGIN CONTAINER -->
<div class="page-container">
    <!-- BEGIN SIDEBAR -->
    <div class="page-sidebar-wrapper">
        <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
        <!-- DOC: Change data-auto-speed="200" to adjust the sub menu slide up/down speed -->
        <div class="page-sidebar navbar-collapse collapse">
            <!-- BEGIN SIDEBAR MENU -->
            <!-- DOC: Apply "page-sidebar-menu-light" class right after "page-sidebar-menu" to enable light sidebar menu style(without borders) -->
            <!-- DOC: Apply "page-sidebar-menu-hover-submenu" class right after "page-sidebar-menu" to enable hoverable(hover vs accordion) sub menu mode -->
            <!-- DOC: Apply "page-sidebar-menu-closed" class right after "page-sidebar-menu" to collapse("page-sidebar-closed" class must be applied to the body element) the sidebar sub menu mode -->
            <!-- DOC: Set data-auto-scroll="false" to disable the sidebar from auto scrolling/focusing -->
            <!-- DOC: Set data-keep-expand="true" to keep the submenues expanded -->
            <!-- DOC: Set data-auto-speed="200" to adjust the sub menu slide up/down speed -->
            <ul class="page-sidebar-menu " data-keep-expanded="false" data-auto-scroll="true" data-slide-speed="200">
                <li <?php if($_SERVER['REQUEST_URI'] == '/'){echo 'class="active open"'; }?> >
                    <a href="/">
                        <i class="icon-home"></i>
                        <span class="title">Home</span>
                    </a>
                </li>
                <li <?php if($_SERVER['REQUEST_URI'] == '/settings' ){echo 'class="active open"'; }?>>
                    <a href="/settings">
                        <i class="icon-settings"></i>
                        <span class="title">Einstellungen</span>
                    </a>
                </li>
                <li <?php if($_SERVER['REQUEST_URI'] == '/imposchu' ){echo 'class="active open"'; }?>>
                    <a href="/import">
                        <i class="icon-settings"></i>
                        <span class="title">Schüler - Import (csv)</span>
                    </a>
                </li>
                <li <?php if($_SERVER['REQUEST_URI'] == '/userList' ){echo 'class="active open"'; }?>>
                    <a href="/userList">
                        <i class="icon-settings"></i>
                        <span class="title">Schüler - Übersicht</span>
                    </a>
                </li>
                <li <?php if($_SERVER['REQUEST_URI'] == '/addUser' ){echo 'class="active open"'; }?>>
                    <a href="/addUser">
                        <i class="icon-settings"></i>
                        <span class="title">Schüler - Hinzufügen</span>
                    </a>
                </li>
                <li <?php if($_SERVER['REQUEST_URI'] == '/importProj' ){echo 'class="active open"'; }?>>
                    <a href="/importProj">
                        <i class="icon-present"></i>
                        <span class="title">Import Projekte (csv)</span>
                    </a>
                </li>
                <li <?php if($_SERVER['REQUEST_URI'] == '/choice' ){echo 'class="active open"'; }?>>
                    <a href="/admchoice">
                        <i class="icon-present"></i>
                        <span class="title">Projekte - Übersicht</span>
                    </a>
                </li>
                <li <?php if($_SERVER['REQUEST_URI'] == '/addProject' ){echo 'class="active open"'; }?>>
                    <a href="/addProject">
                        <i class="icon-present"></i>
                        <span class="title">Projekt anlegen</span>
                    </a>
                </li>
                <li <?php if($_SERVER['REQUEST_URI'] == '/getdata'  ){echo 'class="active open"'; }?>>
                    <a href="/getdata">
                        <i class="icon-bar-chart"></i>
                        <span class="title">Export</span>
                    </a>
                </li>
                <li class="<?php if($_SERVER['REQUEST_URI'] == '/eg-beamer2' OR $_SERVER['REQUEST_URI'] == '/eg-beamer2DEL' ){echo 'class="active open"'; }?>">
                    <a href="/logout">
                        <i class="icon-user"></i>
                        <span class="title">Abmelden</span>
                    </a>
                </li>





            </ul>
            <!-- END SIDEBAR MENU -->
        </div>
    </div>
    <!-- END SIDEBAR -->