<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet box grey-cascade">
                <div class="portlet-title">
                    <div class="caption">
                        <i class="fa fa-globe"></i>Benutzerliste
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="dataTables_wrapper no-footer" id="sample_1_wrapper">
                        <div class="table-scrollable">
                            <table aria-describedby="sample_1_info" role="grid"
                                   class="table table-striped table-bordered table-hover dataTable no-footer"
                                   id="sample_1">
                                <thead>
                                <tr role="row">
                                    <th aria-label="
									 Username
								: activate to sort column ascending" aria-sort="ascending" style="width: 285px;"
                                        colspan="1" rowspan="1" aria-controls="sample_1" tabindex="0"
                                        class="sorting_asc">
                                        Vorname
                                    </th>
                                    <th aria-label="
									 Username
								: activate to sort column ascending" aria-sort="ascending" style="width: 285px;"
                                        colspan="1" rowspan="1" aria-controls="sample_1" tabindex="0"
                                        class="sorting_asc">
                                        Nachname
                                    </th>
                                    <th aria-label="
									 Email
								" style="width: 469px;" colspan="1" rowspan="1" class="sorting_disabled">
                                        Benutzername
                                    </th>
                                    <th aria-label="
									 Points
								" style="width: 174px;" colspan="1" rowspan="1" class="sorting_disabled">
                                        Login
                                    </th>
                                    <th aria-label="
									 Joined
								: activate to sort column ascending" style="width: 254px;" colspan="1" rowspan="1"
                                        aria-controls="sample_1" tabindex="0" class="sorting">
                                        Klasse
                                    </th>
                                    <th aria-label="
									 Status
								" style="width: 258px;" colspan="1" rowspan="1" class="sorting_disabled">
                                        Status
                                    </th>
                                    <th aria-label="
									 Status
								" style="width: 258px;" colspan="1" rowspan="1" class="sorting_disabled">
                                        Optionen
                                    </th>
                                </tr>
                                </thead>
                                <tbody>

                                <?php
                                # results
                                foreach ($results as $row) {
                                    ?>
                                    <tr role="row" class="gradeX odd">
                                        <td class="sorting_1">
                                            <?= $row['vname']  ?>
                                        </td>
                                        <td class="sorting_1">
                                            <?= $row['surename'] ?>
                                        </td>
                                        <td>
                                            <?= $row['loginnumb'] ?>
                                        </td>
                                        <td>
                                            <?php if(isset($row['lasLogin']) AND isset($row['lastlogTime'])){echo $row['lasLogin'].'<br>'. $row['lastlogTime']; }  ?>
                                        </td>
                                        <td class="center">
                                            <?= $row['class'] ?>
                                        </td>
                                        <td>
                                            <?php if ($row['voteDone'] == '1') { ?>
                                                <span class="label label-sm label-success">
									wahl durchgeführt </span>


                                                <?php
                                                $wahl = DB::queryFirstRow("SELECT * FROM voteRelas WHERE userId=%s", $row['id']);

                                                $wahl = DB::queryFirstRow("SELECT title FROM project WHERE id=%s", $wahl['projectId']);
                                                ?><br>
                                                Kurswahl: <b><?=  $wahl['title']?></b>

                                            <?php } elseif ($row['voteDone'] == '0') { ?>
                                                <span class="label label-sm label-danger">
									nicht gewählt </span>
                                            <?php } ?>
                                        </td>
                                        <td>
                                            <form method="post" action="/userlistedit">
                                                <button class="btn blue" type="submit" name="resetVote" value="<?= $row['id'] ?>">
                                                    <i class=" fa-circle-o-notch "></i>
                                                    Wahl zurücksetzen
                                                </button>

                                                <button class="btn red" type="submit" name="delUser" value="<?= $row['id'] ?>">
                                                    <i class=" fa-circle-o-notch "></i>
                                                    Benutzer löschen
                                                </button>
                                            </form>
                                        </td>
                                    </tr>
                                <?php
                                }

                                ?>


                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
</div>

