<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">

        <!-- END SAMPLE PORTLET CONFIGURATION MODAL FORM-->
        <!-- BEGIN PAGE HEADER-->
        <!-- BEGIN PAGE HEAD -->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title">
                <h1>Export der Wahldaten</h1>
            </div>

        </div>
        <!-- END PAGE HEAD -->
        <!-- END PAGE HEADER-->
        <!-- BEGIN PAGE CONTENT-->
        <div class="row">
            <div class="col-md-12">
                <!-- BEGIN PORTLET-->
                <div class="portlet box yellow-crusta">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-gift"></i>
                            Projekterfassung
                        </div>
                    </div>
                    <div class="portlet-body form">
                        <form action="#" id="form-username" class="form-horizontal form-bordered">
                            <div class="form-group ">
                                <label class="col-sm-3 control-label">Projekt - Titel</label>
                                <div class="col-sm-6">
                                    <div class="input-group">
                                        <input type="text" id="typeahead_example_6" name="typeahead_example_6" class="form-control"/>
                                    </div>
                                    <p class="help-block">
                                    </p>
                                </div>
                            </div>
                            <div class="form-group">
                                <label class="col-md-3 control-label">Angebot für Klassen</label>
                                <div class="col-md-4">Von:
                                    <select class="form-control input-xsmall">
                                        <option>5 Kl.</option>
                                        <option>6 Kl.</option>
                                        <option>7 Kl.</option>
                                        <option>8 Kl.</option>
                                        <option>9 Kl.</option>
                                        <option>10 Kl.</option>
                                        <option>11 Kl.</option>
                                    </select>
                                    bis:
                                    <select class="form-control input-xsmall">
                                        <option>5 Kl.</option>
                                        <option>6 Kl.</option>
                                        <option>7 Kl.</option>
                                        <option>8 Kl.</option>
                                        <option>9 Kl.</option>
                                        <option>10 Kl.</option>
                                        <option>11 Kl.</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <label class="col-md-3 control-label">Max. Schüler</label>
                                <div class="col-md-4">
                                    <select class="form-control input-xsmall">
                                        <option>5</option>
                                        <option>6</option>
                                        <option>7</option>
                                        <option>8</option>
                                        <option>9</option>
                                        <option>10</option>
                                        <option>11</option>
                                        <option>12</option>
                                        <option>13</option>
                                        <option>14</option>
                                        <option>15</option>
                                        <option>16</option>
                                        <option>17</option>
                                        <option>18</option>
                                        <option>19</option>
                                        <option>20</option>
                                        <option>21</option>
                                        <option>22</option>
                                        <option>23</option>
                                        <option>24</option>
                                        <option>25</option>
                                        <option>26</option>
                                        <option>27</option>
                                        <option>28</option>
                                        <option>29</option>
                                        <option>29</option>
                                    </select>
                                </div>
                            </div>

                            <div class="form-group">
                                <textarea class="form-control" rows="3=6" placeholder="Projekt - Inhalt"></textarea>
                            </div>

                            <div class="form-actions">
                                <div class="row">
                                    <div class="col-md-offset-3 col-md-9">
                                        <button type="submit" class="btn purple"><i class="fa fa-check"></i> Hinzufügen</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
                <!-- END PORTLET-->
            </div>
        </div>

