<?php
DB::query("SELECT * FROM users WHERE usrgroup=%s", 'usr');
?>

<!-- BEGIN CONTENT -->
<div class="page-content-wrapper">
    <div class="page-content">
        <!-- BEGIN PAGE HEAD -->
        <div class="page-head">
            <!-- BEGIN PAGE TITLE -->
            <div class="page-title">
                <h1>Übersicht
                    <small>Statistiken</small>
                </h1>
            </div>
        </div>
        <!-- END PAGE HEAD -->
        <!-- BEGIN PAGE CONTENT INNER -->
        <div class="row margin-top-10">
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat2">
                    <div class="display">
                        <div class="number">
                            <?php

                            $counter = 0;
                            $results = DB::query("SELECT * FROM project ");
                            foreach ($results as $row) {
                                $counter += $row['maxUsers'];
                            }
                            ?>
                            <h3 class="font-green-sharp"><?= $counter ?>
                                <small class="font-green-sharp"></small>
                            </h3>
                            <small>Gesamte Plätze</small>
                        </div>
                        <div class="icon">
                            <i class="icon-pie-chart"></i>
                        </div>
                    </div>

                    <div class="progress-info">


                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat2">
                    <div class="display">
                        <div class="number">
                            <?php

                            $schuelergew = 0;
                            $gesamtplatz = 0;
                            $results = DB::query("SELECT * FROM project ");
                            foreach ($results as $row) {
                                $schuelergew += $row['nowUsers'];
                                $gesamtplatz += $row['maxUsers'];
                            }

                            DB::query("SELECT * FROM users WHERE voteDone=%s AND usrgroup=%s", '1', 'usr');
                            $VotesDone = DB::count();

                            DB::query("SELECT * FROM users");
                            $allUser = DB::count();
                            ?>
                            <h3 class="font-red-haze"><?= $VotesDone ?></h3>
                            <small>Abgegebene Stimmen</small>
                        </div>
                        <div class="icon">
                            <i class="icon-like"></i>
                        </div>
                    </div>

                    <div class="progress-info">
                        <?php
                        if ($allUser == 0 OR $schuelergew == 0) {
                            $perc = 0;

                        } else {

                            $perc = $VotesDone / $allUser;
                            $perc *= 100;

                            $perc = round($perc);

                            echo $perc;
                        }

                        ?>
                        <div class="progress">
								<span style="width: <?= $perc ?>%;" class="progress-bar progress-bar-success red-haze">
								<span class="sr-only"><?= $perc ?>% change</span>
								</span>
                        </div>
                        <div class="status">
                            <div class="status-title">
                                Schüler die gewählt haben
                            </div>
                            <div class="status-number">
                                <?= $perc ?>%
                            </div>
                        </div>
                    </div>
                </div>
            </div>
            <?php
            DB::query("SELECT * FROM project");
            $projects = DB::count();
            ?>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat2">
                    <div class="display">
                        <div class="number">
                            <h3 class="font-purple-soft"><?= $projects ?></h3>
                            <small>Projekte</small>

                        </div>
                        <div class="icon">
                            <i class="icon-user"></i>
                        </div>
                    </div>
                </div>
            </div>
            <div class="col-lg-3 col-md-3 col-sm-6 col-xs-12">
                <div class="dashboard-stat2">
                    <div class="display">
                        <div class="number">


                            <h3 class="font-purple-soft"><?= $allUser ?></h3>
                            <small>Schüler</small>
                        </div>
                        <div class="icon">
                            <i class="icon-user"></i>
                        </div>
                    </div>
                    <div class="progress-info">

                    </div>
                </div>
            </div>
        </div>
        <!-- END PAGE CONTENT INNER -->


        <div class="row">
            <div class="col-md-6">
                <!-- BEGIN ALERTS PORTLET-->
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs font-green-sharp"></i>
                            <span class="caption-subject font-green-sharp bold uppercase">Passwort ändern</span>
                        </div>
                    </div>
                    <div class="portlet-body">

                        <?php
                        if(isset($_SESSION['success_messagePWCH']) AND $_SESSION['success_messagePWCH'] == true AND $_SESSION['error_messagePWCH'] == false){
                            ?>
                            <div class="alert alert-success">
                                <strong>Success!</strong> Passwort wurde geändert!
                            </div>
                            <?php
                            unset($_SESSION['success_messagePWCH']);
                        }
                        ?>

                        <?php
                        if(isset($_SESSION['error_messagePWCH']) AND $_SESSION['error_messagePWCH'] == true){
                            ?>
                            <div class="alert alert-danger">
                                <strong>Error!</strong> Passwort wurde NICHT geändert!
                            </div>
                            <?php
                            unset($_SESSION['error_messagePWCH']);

                        }
                        ?>

                        <form action="/" method="post">
                            <input class="form-control input-large" placeholder="Ihr aktuelles Passwort" name="passwnow" type="text">

                            <input class="form-control input-large" placeholder="Neues Passwort" name="passwnew" type="text">

                            <input class="form-control input-large" placeholder="Nochmal" name="passwnowWH" type="text">



                            <button type="submit" name="chPassw" class="btn blue">Speichern</button>
                        </form>



                    </div>
                </div>
                <!-- END ALERTS PORTLET-->
            </div>


            <div class="col-md-6">
                <!-- BEGIN ALERTS PORTLET-->
                <div class="portlet light">
                    <div class="portlet-title">
                        <div class="caption">
                            <i class="fa fa-cogs font-green-sharp"></i>
                            <span class="caption-subject font-green-sharp bold uppercase">Benutzer hinzufügen</span>
                        </div>
                    </div>
                    <div class="portlet-body">
                        <?php
                        if(isset($_SESSION['success_message']) AND $_SESSION['success_message'] == true){
                        ?>
                            <div class="alert alert-success">
                                <strong>Success!</strong> Benutzer hinzugefügt
                            </div>
                        <?php
                            unset($_SESSION['success_message']);
                        }
                        ?>

                        <?php
                        if(isset($_SESSION['error_message']) AND $_SESSION['error_message'] == true){
                            ?>
                            <div class="alert alert-danger">
                                <strong>Error!</strong> Benutzer/Kennung ist bereits vorhanden!
                            </div>
                        <?php
                            unset($_SESSION['error_message']);

                        }
                        ?>


                        <form action="/" method="post">
                            <input class="form-control input-large" placeholder="Vorname" name="vname" type="text">

                            <input class="form-control input-large" placeholder="Nachname" name="surename" type="text">

                            <input class="form-control input-large" placeholder="Login / Kennung" name="loginnumb" type="text">

                            <input class="form-control input-large" placeholder="Passwort" name="bday" type="password">



                            <button type="submit" name="addUserAdm" class="btn blue">Speichern</button>
                        </form>







                    </div>
                </div>
                <!-- END ALERTS PORTLET-->
            </div>


        </div>
    </div>
    <!-- END CONTENT -->
</div>
